name: activity_tracker
description: Activity tracker app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6
  reactive_forms: ^14.3.0
  freezed_annotation: ^2.2.0
  riverpod_annotation:
  flutter_svg: ^2.0.5
  dio: ^5.1.1
  reactive_range_slider: ^0.6.0
  bot_toast: ^4.0.3
  reactive_dropdown_search: ^1.0.0
  go_router: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.3.3
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  riverpod_generator:
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/

dependency_overrides:
  test_api: 0.4.16
